name: The Bold Type
favicon: null
layout_spectrum: 0.8683236644137651
typography_spectrum: 0.8503436939790845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.537758847232908
  lightness: 0.5473120943643153
  saturation: 0.0038865928072482347
  rhythmicContrast: 0.9738755787257105
purpose: []
